### ISSUE TITLE
Preload its not working

### ISSUE THREAD

**Issue by eugenioclrc** [dansvel/sveltekit-typescript-postcss-tailwind2#1]
I dont know why but preload func its not working for me... just add this to the $layout or index.svelte
```
<script context="module">
console.log('this works');
export function preload({ host, path, params, query }, session) {
  console.log('preload--- doesnt');
}
</script>
```

**Comment by sutin1234** [comment]
use load function instead preload bro. se more [https://twitter.com/Rich_Harris/status/1346485413997916163](https://twitter.com/Rich_Harris/status/1346485413997916163)

```
<script context="module">
let name;
export function load({page}) {
  name = page.query.name || 'world';  
}
</script>
hello {name}
```
```
<script context="module" lang="ts">
  export async function load({ page }) {
    return {
      props: {
        slug: page.params.slug
      },
    };
  }
</script>

<script>
  export let slug;
</script>

params: {slug} <br />

```

**Comment by bitdom8** [comment]
Thanks. How to conditionally route like "goto"

 <script context="module">
	import { goto } from '$app/navigation';
	export const ssr = false;
	goto("/")
</script>
