### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by eugenioclrc** [dansvel/sveltekit-typescript-postcss-tailwind2#2]
Weird error while building;
> Could not resolve './_app/routes/global.js' from .svelte/build/unoptimized/server/app.js

![Captura de pantalla de 2021-01-06 12-29-14](https://user-images.githubusercontent.com/332426/103786125-d3570780-501a-11eb-9156-62b280189927.png)

**Comment by meigo** [comment]
Quick workaround would be to move global.pcss to components folder and update $layout.svelte
```javascript
import "$components/global.pcss";
```
Or put it somewhere else and update snowpack config.

I like tailwind but v2 seems to have some performance issues: https://github.com/tailwindlabs/tailwindcss/issues/2820
I tested similar setup with tailwind v1.9.6 ( can't use darkMode, @apply with pseudo classes etc) and transpiling was about 3x faster. 
So it kind of steals the speed advantage that snowpack gives you :)

**Comment by eugenioclrc** [comment]
I think that this has work for me;
`import "./_global.pcss";`

Im seeing some perf issues too :(

**Comment by dansvel** [comment]
sorry for slow respon,, 

yeah, i use `_global.pcss`

and i already deploy on netlify,, 

so for this building, i think i already fix it my way,,
