### ISSUE TITLE
Upgrade to latest release of sveltekit

### ISSUE THREAD

**Issue by itswadesh** [dansvel/sveltekit-typescript-postcss-tailwind2#5]
Hi. 8hrs before sveltekit beta was released. There has been some breaking changes. I have fixed those. can you provide me push rights to merge those chagnes

**Comment by dansvel** [comment]
sorry for late response,, i just upgrade it and add some little change,, check the demo and README,,

feel free to close this if you don't have ane other question or response,,
thank you,,
